language: scala

scala:
  - 2.11.5

# Travis does not have the correct environment to run the full test suite.
# Only run the following whitelisted tests:
script: sbt ++$TRAVIS_SCALA_VERSION 'testOnly ParserSpec'

notifications:
  slack:
    secure: P4DrpO26K1dpltdCT4yZcOLxw5xG3ongSOTNWfTTg++xKjMqe5v78laaV/UjDtIPn5JdD6sWuLv9l1kHvnu5QX37cYptDAQyZKJrFdaL05a3sBID9CCGt3PsILrejQSz5wOz6dtEhv6cGCpmyduJxedhjXX9lPapb5wMZC0lJoI=
